/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab1.java3;

import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Bai4 extends javax.swing.JFrame {

    /**
     * Creates new form Bai4
     */
    public Bai4() {
        initComponents();
    }
    public boolean checkNull(){
        if(txt1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Chua nhap gia tri");
            txt1.requestFocus();
            return false;
        }else if(txt2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Chua nhap gia tri");
            txt2.requestFocus();
            return false;
        }else 
            return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        rdCong = new javax.swing.JButton();
        rdTru = new javax.swing.JButton();
        rdNhan = new javax.swing.JButton();
        rdChia = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txtKq = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFirst.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFirst.setText("First number:");

        lblSecond.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSecond.setText("Second number:");

        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResult.setText("Result:");

        rdCong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdCong.setText("+");
        buttonGroup1.add(rdCong);
        rdCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCongActionPerformed(evt);
            }
        });

        rdTru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdTru.setText("-");
        buttonGroup1.add(rdTru);
        rdTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTruActionPerformed(evt);
            }
        });

        rdNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdNhan.setText("*");
        buttonGroup1.add(rdNhan);
        rdNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNhanActionPerformed(evt);
            }
        });

        rdChia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdChia.setText("/");
        buttonGroup1.add(rdChia);
        rdChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdChiaActionPerformed(evt);
            }
        });

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSecond)
                            .addComponent(lblFirst)
                            .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txt2)
                            .addComponent(txtKq))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(rdCong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdTru, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(rdNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rdChia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirst)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecond)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResult)
                    .addComponent(txtKq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdCong)
                    .addComponent(rdTru)
                    .addComponent(rdNhan)
                    .addComponent(rdChia))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTruActionPerformed
            // TODO add your handling code here:
        float so1, so2;
        double ketqua;
        if (checkNull()) {
            so1 = Float.parseFloat(txt1.getText());
            so2 = Float.parseFloat(txt2.getText());
            ketqua = so1 - so2;
            txtKq.setText(ketqua+  "");
        }
    }//GEN-LAST:event_rdTruActionPerformed

    private void rdNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNhanActionPerformed
        // TODO add your handling code here:
          float so1, so2;
        double ketqua;
        if (checkNull()) {
            so1 = Float.parseFloat(txt1.getText());
            so2 = Float.parseFloat(txt2.getText());
            ketqua = so1 * so2;
            txtKq.setText(ketqua + "");
        }
    }//GEN-LAST:event_rdNhanActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt1ActionPerformed

    private void rdCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdCongActionPerformed
        float so1, so2;
        double ketqua;
        if (checkNull()) {
            so1 = Float.parseFloat(txt1.getText());
            so2 = Float.parseFloat(txt2.getText());
            ketqua = so1 + so2;
            txtKq.setText(ketqua + "");
        }
    }//GEN-LAST:event_rdCongActionPerformed

    private void rdChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdChiaActionPerformed
        // TODO add your handling code here:
        float so1, so2;
        double ketqua;
        if (checkNull()) {
            so1 = Float.parseFloat(txt1.getText());
            so2 = Float.parseFloat(txt2.getText());
            ketqua = so1 / so2;
            txtKq.setText(ketqua + "");
        }
    }//GEN-LAST:event_rdChiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JButton rdChia;
    private javax.swing.JButton rdCong;
    private javax.swing.JButton rdNhan;
    private javax.swing.JButton rdTru;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txtKq;
    // End of variables declaration//GEN-END:variables
}
